version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: upminiapp-demobot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DOMAIN=${DOMAIN}
    env_file:
      - .env
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge 